### ISSUE TITLE
Instances of dynamic metrics not handled appropriately

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap-plugin-collector-snmp#18]
Currently when plugin exposes dynamic namespace and receives concrete realization (for example `/a/*/c` is exposed, but `a/b/c` is requested). It's treated as unknown metric.
Fixing this without introducing serious performance issue in my opinion requires deeper rework of plugin's internals.

**Comment by jtlisi** [comment]
I've definitely noticed issues with dynamic metrics with the stability of this plugin. #16 Might be related to this since I've only had the issue with collecting metrics with dynamic namespaces.

**Comment by katarzyna-z** [comment]
[getMetricsToCollect](https://github.com/intelsdi-x/snap-plugin-collector-snmp/blob/master/collector/collector.go#L441)method should be corrected to add support for specific instance of dynamic metric.
Configurations of requested metrics should be selected as the most minimal set of configurations.

For example:

configuration:
```
{
    "mode": "walk",
    "namespace": [
      {
        "source": "string",
        "string": "interfaces"
      },
      {
        "source": "snmp",
        "name": "ifDescr",
        "description": "the textual string containing information about the interface",
        "OID": ".1.3.6.1.2.1.2.2.1.2"
      },
      {
        "source": "string",
        "string": "ifType"
      }
    ],
    "OID": ".1.3.6.1.2.1.2.2.1.3",
    "description": "the type of interface"
 }
```

plugin exposes:
```
/intel/snmp/interfaces/*/ifType
```

user requests:
```
/intel/snmp/interfaces/eth0/ifType
/intel/snmp/interfaces/eth1/ifType
```

so in `getMetricsToCollect` only one configuration should be selected and data for these two requested metrics should be received using the same SNMP requests. 
Received results should be limited to metrics requested by user and these metrics should be returned by `CollectMetrics`.

**Comment by lmroz** [comment]
That's a good start. :+1: but IMO some refactoring would improve plugins performance. I'll open separate issue for this.
