### ISSUE TITLE
Unable to load plugin with example setfile 

### ISSUE THREAD

**Issue by nschmidt4** [intelsdi-x/snap-plugin-collector-snmp#19]
Unable to load the snap snmp plugin collector on a clean install of snap-telemetry when using the example [setfile](https://github.com/intelsdi-x/snap-plugin-collector-snmp/blob/master/examples/setfiles/setfile1.json)

Error when loading the plugin

`# snaptel plugin load snap-plugin-collector-snmp
Error loading plugin:
GetMetricTypes call error : Settings file cannot be unmarshalled, err: json: cannot unmarshal string into Go value of type uint`

Error from snapteld 

`DEBU[2017-02-18T13:19:06-05:00] API request                                   _module=_mgmt-rest index=8 method=POST url=/v1/plugins
DEBU[2017-02-18T13:19:07-05:00] wrote 7993748 to /tmp/snap-plugin-615822242/snap-plugin-collector-snmp 
INFO[2017-02-18T13:19:08-05:00] Loading plugin: /tmp/snap-plugin-615822242/snap-plugin-collector-snmp  _module=_mgmt-rest-v1
INFO[2017-02-18T13:19:08-05:00] plugin load called                            _block=load _module=control
INFO[2017-02-18T13:19:08-05:00] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-snmp
DEBU[2017-02-18T13:19:08-05:00] plugin load timeout set to 3s                 _block=load-plugin _module=control-plugin-mgr path=[snap-plugin-collector-snmp]
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method Decode reply type not a pointer: interface {}  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method Decrypt has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method DecryptKey has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method Encode has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method Encrypt has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method EncryptKey has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method KillChan has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method ListenAddress has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method ListenPort has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method Logger has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method ResetHeartbeat has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method SetEncrypter has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method SetListenAddress has wrong number of ins: 2  _module=plugin-exec io=stderr plugin=
DEBU[2017-02-18T13:19:09-05:00] 2017/02/18 13:19:09 method Token has wrong number of ins: 1  _module=plugin-exec io=stderr plugin=
WARN[2017-02-18T13:19:09-05:00] This plugin is using a deprecated RPC protocol. Find more information here: https://github.com/intelsdi-x/snap/issues/1289   _block=newAvailablePlugin _module=control-aplugin plugin_name=snmp
DEBU[2017-02-18T13:19:09-05:00] time="2017-02-18T13:19:09-05:00" level=error msg="Settings file cannot be unmarshalled, err: json: cannot unmarshal string into Go value of type uint" setfile_content=[91 10 32 32 123 10 32 32 34 109 111 100 101 34 58 32 34 115 105 110 103 108 101 34 44 10 32 32 34 110 97 109 101 115 112 97 99 101 34 58 32 91 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 110 101 116 45 115 105 110 103 108 101 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 105 102 45 115 105 110 103 108 101 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 110 109 112 34 44 32 34 110 97 109 101 34 58 32 34 105 110 116 101 114 102 97 99 101 34 44 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 105 110 116 101 114 102 97 99 101 32 110 97 109 101 34 44 32 34 79 73 68 34 58 32 34 46 49 46 51 46 54 46 49 46 50 46 49 46 50 46 50 46 49 46 50 46 49 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 105 110 100 101 120 34 44 32 34 110 97 109 101 34 58 32 34 105 100 34 44 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 110 117 109 98 101 114 32 102 114 111 109 32 79 73 68 34 44 32 34 111 105 100 95 112 97 114 116 34 58 32 34 49 48 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 105 110 95 111 99 116 101 116 115 34 125 10 32 32 93 44 10 32 32 34 79 73 68 34 58 32 34 46 49 46 51 46 54 46 49 46 50 46 49 46 50 46 50 46 49 46 49 48 46 49 34 44 10 32 32 34 115 99 97 108 101 34 58 32 49 46 48 44 10 32 32 34 115 104 105 102 116 34 58 32 48 44 10 32 32 34 117 110 105 116 34 58 32 34 117 110 105 116 34 44 10 32 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 100 101 115 99 114 105 112 116 105 111 110 32 111 102 32 109 101 116 114 105 99 34 10 32 32 125 44 10 32 123 10 32 32 34 109 111 100 101 34 58 32 34 116 97 98 108 101 34 44 10 32 32 34 110 97 109 101 115 112 97 99 101 34 58 32 91 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 110 101 116 45 116 97 98 108 101 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 105 102 45 116 97 98 108 101 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 110 109 112 34 44 32 34 110 97 109 101 34 58 32 34 105 110 116 101 114 102 97 99 101 34 44 32 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 105 110 116 101 114 102 97 99 101 32 110 97 109 101 34 44 32 34 79 73 68 34 58 32 34 46 49 46 51 46 54 46 49 46 50 46 49 46 50 46 50 46 49 46 50 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 105 110 100 101 120 34 44 32 34 110 97 109 101 34 58 32 34 105 100 34 44 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 110 117 109 98 101 114 32 102 114 111 109 32 79 73 68 34 44 32 34 111 105 100 95 112 97 114 116 34 58 32 34 49 48 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 105 110 95 111 99 116 101 116 115 34 125 10 32 32 93 44 10 32 32 34 79 73 68 34 58 32 34 46 49 46 51 46 54 46 49 46 50 46 49 46 50 46 50 46 49 46 49 48 34 44 10 32 32 34 115 99 97 108 101 34 58 32 49 46 48 44 10 32 32 34 115 104 105 102 116 34 58 32 48 44 10 32 32 34 117 110 105 116 34 58 32 34 117 110 105 116 34 44 10 32 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 100 101 115 99 114 105 112 116 105 111 110 32 32 111 102 32 109 101 116 114 105 99 34 10 32 125 44 10 32 123 10 32 32 34 109 111 100 101 34 58 32 34 119 97 108 107 34 44 10 32 32 34 110 97 109 101 115 112 97 99 101 34 58 32 91 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 110 101 116 45 119 97 108 107 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 105 102 45 119 97 108 107 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 105 110 100 101 120 34 44 32 34 110 97 109 101 34 58 32 34 105 110 100 101 120 57 34 44 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 110 117 109 98 101 114 32 102 114 111 109 32 79 73 68 34 44 32 34 111 105 100 95 112 97 114 116 34 58 32 34 57 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 105 110 100 101 120 34 44 32 34 110 97 109 101 34 58 32 34 105 110 100 101 120 49 48 34 44 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 110 117 109 98 101 114 32 102 114 111 109 32 79 73 68 34 44 32 34 111 105 100 95 112 97 114 116 34 58 32 34 49 48 34 125 44 10 32 32 32 32 123 34 115 111 117 114 99 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 115 116 114 105 110 103 34 58 32 34 118 97 108 117 101 34 125 10 32 32 93 44 10 32 32 34 79 73 68 34 58 32 34 46 49 46 51 46 54 46 49 46 50 46 49 46 50 46 50 46 49 46 34 44 10 32 32 34 115 99 97 108 101 34 58 32 49 46 48 44 10 32 32 34 115 104 105 102 116 34 58 32 48 44 10 32 32 34 117 110 105 116 34 58 32 34 117 110 105 116 34 44 10 32 32 34 100 101 115 99 114 105 112 116 105 111 110 34 58 32 34 100 101 115 99 114 105 112 116 105 111 110 32 111 102 32 109 101 116 114 105 99 34 10 125 10 93 10] setfile_path="BOS1-TPJX-A_set.json"   _module=plugin-exec io=stderr plugin=snmp
ERRO[2017-02-18T13:19:09-05:00] error in getting metric types                 _block=load-plugin _module=control-plugin-mgr error=GetMetricTypes call error : Settings file cannot be unmarshalled, err: json: cannot unmarshal string into Go value of type uint plugin-type=collector
ERRO[2017-02-18T13:19:09-05:00] GetMetricTypes call error : Settings file cannot be unmarshalled, err: json: cannot unmarshal string into Go value of type uint  _module=_mgmt-rest-v1
DEBU[2017-02-18T13:19:09-05:00] Removing file (/tmp/snap-plugin-615822242/snap-plugin-collector-snmp)  _module=_mgmt-rest-v1
DEBU[2017-02-18T13:19:09-05:00] API response                                  _module=_mgmt-rest index=8 method=POST status=Internal Server Error status-code=500 url=/v1/plugins
`

For troubleshooting purposes I was able to get the plugin loaded and working with a single OID using the following setfile 

`
{
  "mode": "single",
  "namespace": [
    {"source": "snmp", "name": "interface", "description": "In Packets", "OID": ".1.3.6.1.2.1.2.2.1.11.543"},
    {"source": "string", "string": "InPackets"}
  ],
  "OID": ".1.3.6.1.2.1.2.2.1.11.543"
}
]`

Environment

`# snapteld -v
snapteld version 1.1.0`

`# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"`

`# uname -a
Linux schmidtvm 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Slack Conversation with Joel - https://intelsdi-x.slack.com/archives/snap-users/p1487442131000525

**Comment by katarzyna-z** [comment]
I 've parsed `setfile_content` from log which you attached using this: 
```golang
package main

import "fmt"

func main(){

	setfile_content := []byte{91,10,32,32,123,10,32,32,34,109,111,100,101,34,58,32,34,115,105,110,103,108,101,34,44,10,32,32,34,110,97,109,101,115,112,97,99,101,34,58,32,91,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,110,101,116,45,115,105,110,103,108,101,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,105,102,45,115,105,110,103,108,101,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,110,109,112,34,44,32,34,110,97,109,101,34,58,32,34,105,110,116,101,114,102,97,99,101,34,44,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,105,110,116,101,114,102,97,99,101,32,110,97,109,101,34,44,32,34,79,73,68,34,58,32,34,46,49,46,51,46,54,46,49,46,50,46,49,46,50,46,50,46,49,46,50,46,49,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,105,110,100,101,120,34,44,32,34,110,97,109,101,34,58,32,34,105,100,34,44,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,110,117,109,98,101,114,32,102,114,111,109,32,79,73,68,34,44,32,34,111,105,100,95,112,97,114,116,34,58,32,34,49,48,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,105,110,95,111,99,116,101,116,115,34,125,10,32,32,93,44,10,32,32,34,79,73,68,34,58,32,34,46,49,46,51,46,54,46,49,46,50,46,49,46,50,46,50,46,49,46,49,48,46,49,34,44,10,32,32,34,115,99,97,108,101,34,58,32,49,46,48,44,10,32,32,34,115,104,105,102,116,34,58,32,48,44,10,32,32,34,117,110,105,116,34,58,32,34,117,110,105,116,34,44,10,32,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,100,101,115,99,114,105,112,116,105,111,110,32,111,102,32,109,101,116,114,105,99,34,10,32,32,125,44,10,32,123,10,32,32,34,109,111,100,101,34,58,32,34,116,97,98,108,101,34,44,10,32,32,34,110,97,109,101,115,112,97,99,101,34,58,32,91,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,110,101,116,45,116,97,98,108,101,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,105,102,45,116,97,98,108,101,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,110,109,112,34,44,32,34,110,97,109,101,34,58,32,34,105,110,116,101,114,102,97,99,101,34,44,32,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,105,110,116,101,114,102,97,99,101,32,110,97,109,101,34,44,32,34,79,73,68,34,58,32,34,46,49,46,51,46,54,46,49,46,50,46,49,46,50,46,50,46,49,46,50,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,105,110,100,101,120,34,44,32,34,110,97,109,101,34,58,32,34,105,100,34,44,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,110,117,109,98,101,114,32,102,114,111,109,32,79,73,68,34,44,32,34,111,105,100,95,112,97,114,116,34,58,32,34,49,48,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,105,110,95,111,99,116,101,116,115,34,125,10,32,32,93,44,10,32,32,34,79,73,68,34,58,32,34,46,49,46,51,46,54,46,49,46,50,46,49,46,50,46,50,46,49,46,49,48,34,44,10,32,32,34,115,99,97,108,101,34,58,32,49,46,48,44,10,32,32,34,115,104,105,102,116,34,58,32,48,44,10,32,32,34,117,110,105,116,34,58,32,34,117,110,105,116,34,44,10,32,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,100,101,115,99,114,105,112,116,105,111,110,32,32,111,102,32,109,101,116,114,105,99,34,10,32,125,44,10,32,123,10,32,32,34,109,111,100,101,34,58,32,34,119,97,108,107,34,44,10,32,32,34,110,97,109,101,115,112,97,99,101,34,58,32,91,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,110,101,116,45,119,97,108,107,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,105,102,45,119,97,108,107,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,105,110,100,101,120,34,44,32,34,110,97,109,101,34,58,32,34,105,110,100,101,120,57,34,44,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,110,117,109,98,101,114,32,102,114,111,109,32,79,73,68,34,44,32,34,111,105,100,95,112,97,114,116,34,58,32,34,57,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,105,110,100,101,120,34,44,32,34,110,97,109,101,34,58,32,34,105,110,100,101,120,49,48,34,44,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,110,117,109,98,101,114,32,102,114,111,109,32,79,73,68,34,44,32,34,111,105,100,95,112,97,114,116,34,58,32,34,49,48,34,125,44,10,32,32,32,32,123,34,115,111,117,114,99,101,34,58,32,34,115,116,114,105,110,103,34,44,32,34,115,116,114,105,110,103,34,58,32,34,118,97,108,117,101,34,125,10,32,32,93,44,10,32,32,34,79,73,68,34,58,32,34,46,49,46,51,46,54,46,49,46,50,46,49,46,50,46,50,46,49,46,34,44,10,32,32,34,115,99,97,108,101,34,58,32,49,46,48,44,10,32,32,34,115,104,105,102,116,34,58,32,48,44,10,32,32,34,117,110,105,116,34,58,32,34,117,110,105,116,34,44,10,32,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,100,101,115,99,114,105,112,116,105,111,110,32,111,102,32,109,101,116,114,105,99,34,10,125,10,93,10}
	fmt.Println(string(setfile_content))
}
```
and I've received this form of setfile:
```json
[
  {
  "mode": "single",
  "namespace": [
    {"source": "string", "string": "net-single"},
    {"source": "string", "string": "if-single"},
    {"source": "snmp", "name": "interface", "description": "interface name", "OID": ".1.3.6.1.2.1.2.2.1.2.1"},
    {"source": "index", "name": "id", "description": "number from OID", "oid_part": "10"},
    {"source": "string", "string": "in_octets"}
  ],
  "OID": ".1.3.6.1.2.1.2.2.1.10.1",
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description of metric"
  },
 {
  "mode": "table",
  "namespace": [
    {"source": "string", "string": "net-table"},
    {"source": "string", "string": "if-table"},
    {"source": "snmp", "name": "interface",  "description": "interface name", "OID": ".1.3.6.1.2.1.2.2.1.2"},
    {"source": "index", "name": "id", "description": "number from OID", "oid_part": "10"},
    {"source": "string", "string": "in_octets"}
  ],
  "OID": ".1.3.6.1.2.1.2.2.1.10",
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description  of metric"
 },
 {
  "mode": "walk",
  "namespace": [
    {"source": "string", "string": "net-walk"},
    {"source": "string", "string": "if-walk"},
    {"source": "index", "name": "index9", "description": "number from OID", "oid_part": "9"},
    {"source": "index", "name": "index10", "description": "number from OID", "oid_part": "10"},
    {"source": "string", "string": "value"}
  ],
  "OID": ".1.3.6.1.2.1.2.2.1.",
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description of metric"
}
]

```
and I see the difference between your setfile and [setfile1.json](https://github.com/intelsdi-x/snap-plugin-collector-snmp/blob/master/examples/setfiles/setfile1.json) in your setfile `oid_part` is string but should be uint.

Please change `oid_part` to uint in your setfile and let me know if you can now load plugin.

**Comment by mkleina** [comment]
@nschmidt4, does it resolved your problem?

**Comment by nanliu** [comment]
@nschmidt4, did you get a chance to try this again?

**Comment by nschmidt4** [comment]
I am now able to load the snmp plugin. Thank you all.
